### PR TITLE
Merging to prod

### PR DESCRIPTION
**Pull request by AlexJerabek**
Tested the moved formerly-preview snippets in Script Lab. Everything looks good.

### CODE REVIEW

**Comment by AlexJerabek** [comment]
@kbrandl I updated the prod branch a couple days ago. Any idea why it's still trying to merge changes from a month ago?

**Comment by kbrandl** [comment]
@AlexJerabek -- the reason that all of the previously-merged-into-prod changes are showing up in this PR is likely because you used **Squash and merge** to merge the previous PR into **prod** (#206).  When you merge a PR using **Squash and merge**, none of the individual commits in that PR get added to the destination branch -- so **prod** doesn't have any knowledge of those individual commits and the next time you open a PR to merge into **prod**, you'll see all the old commits again (because **prod** thinks it doesn't have them yet). 

Take aways:
- When merging a PR into **master**, always use **Squash and merge**.
- When merging a PR into **prod** / **live** always use **Merge**.

So, select **Merge** for this PR (#209) and you shouldn't see any of these same commits again in future PRs to **prod**.

**Comment by AlexJerabek** [comment]
Hey @kbrandl, I'm not sure how to fix this merge conflict. Usually I'm all for experimenting until something works, but the Ignite show floor feels like the wrong place to do that. Any chance I can get some help here?

**Comment by kbrandl** [comment]
Hey @AlexJerabek no problem.  I'll take a look at this now.

**Comment by kbrandl** [comment]
@Rick-Kirkham it's a mystery to me as to why there's a merge conflict on this PR in the first place, let alone how to resolve it. Would you perhaps have time to take a look and let us know your thoughts?

**Comment by Rick-Kirkham** [comment]
@kbrandl I don't see what the issue is either. It was citing the data-validation.md file as having conflicts, but the UI buttons for working with conflicts were grayed out. I followed the instructions on this page (at the time) for doing a manual merge from master to prod. It seems to have worked.

**Comment by kbrandl** [comment]
@Rick-Kirkham thank you for the help with this!

**Pull request merged**
