### PR TITLE
Update selection-changed.yaml

### PR DESCRIPTION
**Pull request by jakobpn**

### CODE REVIEW

**Comment by Zlatkovsky** [comment]
@jakobpn , I think the *scenario* for remove all was good.  It's just that now you need to keep a reference to all of your handlers (e.g., in an array), and do a remove all by calling "remove" on each of them (and emptying out the array).

**Comment by Zlatkovsky** [comment]
@jakobpn , ping

**Comment by jakobpn** [comment]
Planning to work on it this morning as I am testing the latest build of Script Lab.

**Comment by jakobpn** [comment]
Thx Michael!

**Pull request merged**
